
const SB_URL='https://rmtysrytveexshwzenxj.supabase.co';
const KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJtdHlzcnl0dmVleHNod3plbnhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1MjQ3OTYsImV4cCI6MjA5MjEwMDc5Nn0.5FzzJ1rg-uRG4jAGZ75xVT3i3NH0m6J_tDeOS4GxyT8';
const RH={'apikey':KEY,'Authorization':'Bearer '+KEY};
const JH={'Content-Type':'application/json','apikey':KEY,'Authorization':'Bearer '+KEY,'Prefer':'return=minimal'};
const STORAGE=SB_URL+'/storage/v1';
let songs=[], selectedId=null, selectedFiles=[], selectedManifest=null;
function esc(s){return String(s||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(s){return String(s||'').normalize('NFC').replace(/[\s_\-\[\](){}]+/g,'').trim().toLowerCase()}
function log(t){const el=document.getElementById('log');el.textContent += '\n'+t;el.scrollTop=el.scrollHeight}
function isImageName(name){return /\.(png|jpe?g|webp|gif)$/i.test(name||'')}
function extOf(path){const m=String(path||'').match(/\.([a-z0-9]+)$/i);return m?m[1].toLowerCase():'png'}
function versionId(){return 'v'+Date.now().toString(36)+Math.random().toString(36).slice(2,7)}
function safeFileName(page,ext){return `${Date.now()}_${Number(page||1)-1}.${ext||'png'}`}
function publicUrl(path){return `${STORAGE}/object/public/scores/${encodeURIComponent(path).replaceAll('%2F','/')}`}
function manifestPath(songId){return `${songId}/score_manifest.json`}
async function rest(path,opt={}){const r=await fetch(SB_URL+'/rest/v1/'+path,{headers:RH,...opt});if(!r.ok)throw new Error(await r.text());const t=await r.text();return t?JSON.parse(t):[]}
async function patchSong(id,body){await fetch(`${SB_URL}/rest/v1/songs?id=eq.${id}`,{method:'PATCH',headers:JH,body:JSON.stringify({...body,updated_at:new Date().toISOString()})})}
async function listStorage(prefix){const r=await fetch(`${STORAGE}/object/list/scores`,{method:'POST',headers:{...RH,'Content-Type':'application/json'},body:JSON.stringify({prefix,limit:1000,sortBy:{column:'name',order:'asc'}})});if(!r.ok)return [];return await r.json()}
async function listStorageRecursive(prefix,depth=0){if(depth>5)return [];const rows=await listStorage(prefix);let out=[];for(const item of rows){if(!item||!item.name)continue;const full=prefix+item.name;const looksFolder=!item.id && !item.metadata && !/\.[a-z0-9]{2,5}$/i.test(item.name);if(looksFolder){out=out.concat(await listStorageRecursive(full.replace(/\/+$/,'')+'/',depth+1));}else if(isImageName(item.name)){out.push({storage_path:full,file_name:item.name});}}return out}
async function fetchBlob(path){const r=await fetch(publicUrl(path));if(!r.ok)throw new Error('파일 다운로드 실패: '+path);return await r.blob()}
async function uploadBlob(path,blob){const r=await fetch(`${STORAGE}/object/scores/${encodeURIComponent(path).replaceAll('%2F','/')}`,{method:'POST',headers:{...RH,'Content-Type':blob.type||'application/octet-stream','x-upsert':'true'},body:blob});if(!r.ok)throw new Error(await r.text())}
async function deleteStorage(path){await fetch(`${STORAGE}/object/scores`,{method:'DELETE',headers:{...RH,'Content-Type':'application/json'},body:JSON.stringify({prefixes:[path]})})}
async function upsertScoreRecord(songId,path,pageNo,versionName,versionKey,oldPath){
  const body={song_id:songId,storage_path:path,file_name:path.split('/').pop(),page_no:Number(pageNo||1),score_version:versionName||'',score_key:versionKey||'',updated_at:new Date().toISOString()};
  try{
    if(oldPath){await fetch(`${SB_URL}/rest/v1/song_score_files?storage_path=eq.${encodeURIComponent(oldPath)}`,{method:'PATCH',headers:JH,body:JSON.stringify(body)});}
    else{await fetch(`${SB_URL}/rest/v1/song_score_files`,{method:'POST',headers:JH,body:JSON.stringify(body)});}
  }catch(e){log('ℹ️ song_score_files 기록은 선택 사항이라 건너뜀: '+e.message)}
}
async function deleteScoreRecord(path){try{await fetch(`${SB_URL}/rest/v1/song_score_files?storage_path=eq.${encodeURIComponent(path)}`,{method:'DELETE',headers:JH})}catch(e){}}
async function loadManifest(songId){
  try{const r=await fetch(publicUrl(manifestPath(songId))+'?t='+Date.now());if(!r.ok)throw new Error('no manifest');return await r.json()}catch(e){return {song_id:String(songId),updated_at:null,versions:[],files:[]}}
}
async function saveManifest(songId,manifest){
  manifest.song_id=String(songId);manifest.updated_at=new Date().toISOString();
  const blob=new Blob([JSON.stringify(manifest,null,2)],{type:'application/json'});
  await uploadBlob(manifestPath(songId),blob);
}
function ensureVersion(manifest,name,key){
  name=(name||'기본').trim();key=(key||'').trim();
  let v=(manifest.versions||[]).find(x=>String(x.name||'')===name && String(x.key||'')===key);
  if(!v){v={id:versionId(),name,key,created_at:new Date().toISOString()};manifest.versions=manifest.versions||[];manifest.versions.push(v)}
  return v;
}
async function scan(){const btn=document.getElementById('scanBtn');btn.disabled=true;document.getElementById('log').textContent='📋 곡 목록 불러오는 중...';try{songs=await rest('songs?select=id,name,key,bpm,bpm_min,bpm_max,status,has_score,score_version&order=name&limit=3000');for(const s of songs){const files=await listStorageRecursive(String(s.id).replace(/\/+$/,'')+'/');s._score_count=files.length;s._version_groups=[...new Set(files.map(f=>String(f.storage_path).split('/')[1]||'root'))].length;}log(`✅ ${songs.length}곡 불러옴`);renderSongList();}catch(e){log('✗ 오류: '+e.message)}btn.disabled=false}
function renderSongList(){const q=norm(document.getElementById('q').value);const mode=document.getElementById('mode').value;let rows=songs.filter(s=>!q||norm(s.name).includes(q));if(mode==='withScore')rows=rows.filter(s=>s._score_count>0||s.has_score);if(mode==='multi')rows=rows.filter(s=>(s._score_count||0)>1 || (s._version_groups||0)>1);const box=document.getElementById('songList');if(!rows.length){box.innerHTML='<div class="empty">표시할 곡이 없습니다.</div>';return}box.innerHTML=rows.map(s=>`<div class="song-row ${String(s.id)===String(selectedId)?'active':''}" onclick="selectSong('${esc(String(s.id))}')"><div class="song-title">${esc(s.name)}</div><div class="meta">ID ${esc(s.id)} · Key ${esc(s.key||'-')} · 악보 ${s._score_count||0}개 · 그룹 ${s._version_groups||0}</div>${(s._score_count||0)>1?'<span class="pill warn">정리 필요</span>':''}${s.score_version?`<span class="pill">${esc(s.score_version)}</span>`:''}</div>`).join('')}
async function selectSong(id){selectedId=String(id);renderSongList();await renderSelected()}
function selectedSong(){return songs.find(s=>String(s.id)===String(selectedId))}
async function renderSelected(){const s=selectedSong();if(!s){document.getElementById('detail').innerHTML='<div class="empty">곡을 선택해주세요.</div>';return}document.getElementById('detail').innerHTML='<div class="empty">악보와 JSON 불러오는 중...</div>';selectedFiles=await listStorageRecursive(String(s.id).replace(/\/+$/,'')+'/');selectedManifest=await loadManifest(s.id);document.getElementById('detail').innerHTML=detailHtml(s);}
function detailHtml(s){const bpm=s.bpm_min||s.bpm_max?`${s.bpm_min||''}${s.bpm_max&&s.bpm_max!==s.bpm_min?'~'+s.bpm_max:''}`:(s.bpm||'-');return `<div class="box-title">${esc(s.name)}</div><div class="meta">ID ${esc(s.id)} · Key ${esc(s.key||'-')} · BPM ${esc(bpm)} · Storage 파일명은 숫자/영문 유지</div><div style="display:flex;gap:6px;flex-wrap:wrap;margin:10px 0"><button class="good" onclick="writeManifestFromCurrent()">현재 파일로 JSON 재생성</button><button class="warn" onclick="normalizeSelectedSong()">이 곡 파일 정리 실행</button><button onclick="downloadManifest()">JSON 보기/다운로드</button></div><div class="panel"><div class="box-title">선택 파일 이동/버전 지정</div><div class="form-grid"><input id="targetSongQuery" placeholder="이동 대상 곡 검색" oninput="renderTargetOptions()"><select id="targetSong"></select><input id="targetKey" placeholder="악보 Key, 예: A"></div><div class="form-grid" style="margin-top:8px"><input id="targetVersion" placeholder="버전명, 예: 전주1 / 전주2 / 기본"><input id="targetPage" type="number" min="1" value="1" placeholder="페이지 번호"><button class="primary" onclick="moveCheckedFiles()">선택 악보 이동/정리</button></div><p>파일명은 한글로 바꾸지 않고 <b>songId/versionId/1776703925124_0.png</b> 형식으로 안전하게 저장합니다. 의미 정보는 JSON에 기록됩니다.</p></div>${selectedFiles.length?`<div class="files">${selectedFiles.map((f,i)=>fileHtml(f,i)).join('')}</div>`:'<div class="empty">이 곡에는 Storage 악보 이미지가 없습니다.</div>'}<div class="panel danger-zone"><div class="box-title">JSON 상태</div><pre style="white-space:pre-wrap;font-size:11px;color:#cbd5e1;max-height:260px;overflow:auto">${esc(JSON.stringify(selectedManifest,null,2))}</pre></div>`}
function fileHtml(f,i){const url=publicUrl(f.storage_path);const meta=(selectedManifest.files||[]).find(x=>x.storage_path===f.storage_path)||{};return `<div class="file"><div class="thumb"><img src="${url}" loading="lazy" onerror="this.parentElement.textContent='미리보기 실패'"></div><div class="file-body"><label style="display:flex;gap:6px;align-items:center;font-size:12px"><input type="checkbox" class="fileCheck" value="${esc(f.storage_path)}"> 선택</label><div class="file-name">${esc(f.file_name)}</div><div class="file-path">${esc(f.storage_path)}</div><div class="meta">JSON: ${esc(meta.version_name||'-')} / ${esc(meta.key||'-')} / p.${esc(meta.page_no||'-')}</div><div class="file-actions"><button onclick="openPreview('${encodeURIComponent(url)}')">보기</button><button class="danger" onclick="deleteOne('${encodeURIComponent(f.storage_path)}')">삭제</button></div></div></div>`}
function renderTargetOptions(){const q=norm(document.getElementById('targetSongQuery').value);let rows=songs.filter(s=>!q||norm(s.name).includes(q)).slice(0,80);if(!rows.some(s=>String(s.id)===String(selectedId))){const cur=selectedSong();if(cur)rows.unshift(cur)}document.getElementById('targetSong').innerHTML=rows.map(s=>`<option value="${esc(s.id)}">${esc(s.name)} / ${esc(s.key||'-')} / ${esc(s.id)}</option>`).join('')}
async function writeManifestFromCurrent(){const s=selectedSong();if(!s)return;const mf={song_id:String(s.id),updated_at:new Date().toISOString(),versions:[],files:[]};const v=ensureVersion(mf,s.score_version||'기본',s.key||'');selectedFiles.forEach((f,i)=>mf.files.push({storage_path:f.storage_path,file_name:f.file_name,version_id:v.id,version_name:v.name,key:v.key,page_no:i+1,display_name:`${s.name} ${v.key} ${v.name} ${i+1}p`}));await saveManifest(s.id,mf);selectedManifest=mf;await patchSong(s.id,{has_score:selectedFiles.length>0,status:selectedFiles.length>0?'ready':(s.status||'plan')});log(`✓ ${s.name} JSON 재생성 완료`);await renderSelected()}
async function moveOneFile(oldPath,targetSongId,versionName,key,pageNo){const ext=extOf(oldPath);let targetManifest=await loadManifest(targetSongId);const v=ensureVersion(targetManifest,versionName||'기본',key||'');const newPath=`${targetSongId}/${v.id}/${safeFileName(pageNo,ext)}`;const blob=await fetchBlob(oldPath);await uploadBlob(newPath,blob);await deleteStorage(oldPath);targetManifest.files=targetManifest.files||[];targetManifest.files=targetManifest.files.filter(x=>x.storage_path!==oldPath && x.storage_path!==newPath);const targetSong=songs.find(x=>String(x.id)===String(targetSongId));targetManifest.files.push({storage_path:newPath,file_name:newPath.split('/').pop(),version_id:v.id,version_name:v.name,key:v.key,page_no:Number(pageNo||1),display_name:`${targetSong?.name||''} ${v.key} ${v.name} ${pageNo||1}p`,moved_from:oldPath,updated_at:new Date().toISOString()});await saveManifest(targetSongId,targetManifest);await upsertScoreRecord(targetSongId,newPath,pageNo,v.name,v.key,oldPath);if(String(targetSongId)!==String(selectedId)){let oldManifest=await loadManifest(selectedId);oldManifest.files=(oldManifest.files||[]).filter(x=>x.storage_path!==oldPath);await saveManifest(selectedId,oldManifest);await deleteScoreRecord(oldPath);}return newPath}
async function moveCheckedFiles(){const checked=[...document.querySelectorAll('.fileCheck:checked')].map(x=>x.value);if(!checked.length){alert('이동/정리할 악보를 선택해주세요.');return}const targetSongId=document.getElementById('targetSong').value||selectedId;const key=document.getElementById('targetKey').value.trim()||selectedSong()?.key||'';const version=document.getElementById('targetVersion').value.trim()||'기본';let page=Number(document.getElementById('targetPage').value||1);if(!confirm(`${checked.length}개 악보를 정리할까요?\n\n대상 곡 ID: ${targetSongId}\nKey: ${key}\n버전: ${version}\n\n실제 파일명은 숫자/영문 안전 이름으로 새로 저장됩니다.`))return;try{for(const oldPath of checked){const np=await moveOneFile(oldPath,targetSongId,version,key,page++);log(`✓ 이동/정리: ${oldPath} → ${np}`)}await patchSong(targetSongId,{has_score:true,status:'ready'});await refreshSongCounts();await renderSelected();}catch(e){log('✗ 이동 실패: '+e.message)}}
async function normalizeSelectedSong(){const s=selectedSong();if(!s||!selectedFiles.length)return;const version=prompt('이 곡 악보의 버전명을 입력하세요. 예: 기본 / 전주1 / 전주2',s.score_version||'기본');if(version===null)return;const key=prompt('이 악보의 Key를 입력하세요.',s.key||'')||s.key||'';if(!confirm('현재 곡 안의 모든 악보를 안전한 숫자 파일명 + JSON 기준으로 정리합니다. 계속할까요?'))return;try{let page=1;for(const f of [...selectedFiles]){await moveOneFile(f.storage_path,s.id,version,key,page++);}await patchSong(s.id,{has_score:true,status:'ready'});await refreshSongCounts();await renderSelected();log(`✓ ${s.name} 파일 정리 완료`)}catch(e){log('✗ 정리 실패: '+e.message)}}
async function deleteOne(encodedPath){const path=decodeURIComponent(encodedPath);if(!confirm(`삭제할까요?\n${path}`))return;try{await deleteStorage(path);await deleteScoreRecord(path);let mf=await loadManifest(selectedId);mf.files=(mf.files||[]).filter(x=>x.storage_path!==path);await saveManifest(selectedId,mf);await refreshSongCounts();await renderSelected();log('🗑 삭제 완료: '+path)}catch(e){log('✗ 삭제 실패: '+e.message)}}
async function refreshSongCounts(){for(const s of songs){if(String(s.id)===String(selectedId)){const files=await listStorageRecursive(String(s.id).replace(/\/+$/,'')+'/');s._score_count=files.length;s._version_groups=[...new Set(files.map(f=>String(f.storage_path).split('/')[1]||'root'))].length;s.has_score=files.length>0;}}renderSongList()}
function downloadManifest(){const s=selectedSong();if(!s||!selectedManifest)return;const blob=new Blob([JSON.stringify(selectedManifest,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`score_manifest_${s.id}.json`;a.click();URL.revokeObjectURL(a.href)}
function openPreview(u){document.getElementById('previewImg').src=decodeURIComponent(u);document.getElementById('preview').classList.add('show')}
function closePreview(){document.getElementById('preview').classList.remove('show');document.getElementById('previewImg').src=''}
setTimeout(()=>{renderTargetOptions()},300);
