
const SUPABASE_URL='https://rmtysrytveexshwzenxj.supabase.co';
const KEY='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJIUzI1NiIsInJlZiI6InJtdHlzcnl0dmVleHNod3plbnhqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzY1MjQ3OTYsImV4cCI6MjA5MjEwMDc5Nn0.5FzzJ1rg-uRG4jAGZ75xVT3i3NH0m6J_tDeOS4GxyT8'.replace('eyJpc3MiOiJIUzI1NiIsInJlZiI','eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI');
const REST=SUPABASE_URL+'/rest/v1/';
const STORAGE=SUPABASE_URL+'/storage/v1';
const HEADERS={'Content-Type':'application/json','apikey':KEY,'Authorization':'Bearer '+KEY,'Prefer':'return=representation'};
const STOR_HEADERS={'apikey':KEY,'Authorization':'Bearer '+KEY};
let songs=[], selected=null, versions=[], dbFiles=[], storageFiles=[], activeTab='versions';
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function norm(s){return String(s||'').normalize('NFC').replace(/\s+/g,' ').trim().toLowerCase()}
function isImagePath(p){return /\.(png|jpe?g|webp|gif)$/i.test(String(p||''))}
function publicUrl(path){return `${SUPABASE_URL}/storage/v1/object/public/scores/${String(path||'').split('/').map(encodeURIComponent).join('/')}`}
function toast(t){const el=document.getElementById('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)}
function log(t){const el=document.getElementById('log');el.textContent=(new Date().toLocaleTimeString()+'  '+t+'\n'+el.textContent).slice(0,3000)}
async function api(method,path,body){const r=await fetch(REST+path,{method,headers:HEADERS,body:body?JSON.stringify(body):undefined});if(!r.ok)throw new Error(await r.text());const txt=await r.text();return txt?JSON.parse(txt):null}
async function storageList(prefix=''){const r=await fetch(`${STORAGE}/object/list/scores`,{method:'POST',headers:{...STOR_HEADERS,'Content-Type':'application/json'},body:JSON.stringify({prefix,limit:1000,offset:0,sortBy:{column:'name',order:'asc'}})});if(!r.ok)throw new Error(await r.text());return await r.json()}
async function storageRemove(paths){if(!paths.length)return;const r=await fetch(`${STORAGE}/object/scores`,{method:'DELETE',headers:{...STOR_HEADERS,'Content-Type':'application/json'},body:JSON.stringify({prefixes:paths})});if(!r.ok)throw new Error(await r.text());return await r.json()}
async function loadSongs(){try{document.getElementById('schemaNotice').textContent='곡 목록을 불러오는 중...';songs=await api('GET','songs?select=*&order=name.asc');await api('GET','song_score_versions?select=id&limit=1');await api('GET','song_score_files?select=id&limit=1');document.getElementById('schemaNotice').innerHTML='✅ 악보 버전 관리 DB 연결 완료. Storage 파일명은 그대로 두고 DB 연결만 정리합니다.';renderSongs()}catch(e){document.getElementById('schemaNotice').innerHTML='⚠️ 악보 버전관리 테이블 확인 실패. <b>phase2b_schema.sql</b> 실행 여부를 확인하세요.<br><small>'+esc(e.message)+'</small>';renderSongs()}}
function renderSongs(){const q=norm(document.getElementById('q').value);const list=songs.filter(s=>!q||norm(s.name).includes(q)).slice(0,400);document.getElementById('songList').innerHTML=list.map(s=>`<button class="song ${selected&&String(selected.id)===String(s.id)?'on':''}" onclick="selectSong('${s.id}')"><b>${esc(s.name)}</b><small>Key ${esc(s.key||'-')} · BPM ${esc(s.bpm_min||s.bpm||'-')}${s.bpm_max?'~'+esc(s.bpm_max):''} · ${s.has_score?'악보 있음':'악보 없음'}</small></button>`).join('')||'<div class="empty">검색 결과 없음</div>'}
async function selectSong(id){selected=songs.find(s=>String(s.id)===String(id));renderSongs();document.getElementById('workArea').style.display='block';document.getElementById('selectedHead').innerHTML=`<h2 style="margin:0 0 4px">${esc(selected.name)}</h2><p>Key ${esc(selected.key||'-')} · BPM ${esc(selected.bpm_min||selected.bpm||'-')}${selected.bpm_max?'~'+esc(selected.bpm_max):''} · song_id: <span class="mini">${esc(selected.id)}</span></p>`;await reloadSelected()}
async function reloadSelected(){if(!selected)return;try{versions=await api('GET',`song_score_versions?select=*&song_id=eq.${selected.id}&order=is_default.desc,created_at.asc`)}catch(e){versions=[];log('버전 조회 실패: '+e.message)}try{dbFiles=await api('GET',`song_score_files?select=*&song_id=eq.${selected.id}&order=page_no.asc,created_at.asc`)}catch(e){dbFiles=[];log('DB 파일 조회 실패: '+e.message)}try{storageFiles=await collectStorageFiles(selected.id)}catch(e){storageFiles=[];log('Storage 조회 실패: '+e.message)}renderAll()}
async function collectStorageFiles(songId){const out=[];async function walk(prefix){const items=await storageList(prefix);for(const it of items){const path=(prefix?prefix.replace(/\/$/,'')+'/':'')+it.name;if(it.id||it.metadata){if(isImagePath(path))out.push({storage_path:path,file_name:it.name,size:it.metadata?.size||0,updated_at:it.updated_at||it.created_at||''})}else{await walk(path)}}}
await walk(String(songId));return out}
function setTab(tab){activeTab=tab;document.querySelectorAll('.tab').forEach(b=>b.classList.toggle('on',b.dataset.tab===tab));renderAll()}
function renderAll(){document.getElementById('tabVersions').style.display=activeTab==='versions'?'block':'none';document.getElementById('tabUnlinked').style.display=activeTab==='unlinked'?'block':'none';document.getElementById('tabRepair').style.display=activeTab==='repair'?'block':'none';renderMoveTarget();renderVersions();renderUnlinked();renderRepair()}
function renderMoveTarget(){const sel=document.getElementById('moveTarget');sel.innerHTML=versions.map(v=>`<option value="${v.id}">${esc(v.version_name)} · ${esc(v.score_key||'-')}</option>`).join('')||'<option value="">먼저 버전을 만드세요</option>'}
function fileCheckbox(f, origin){const key=origin+'|'+f.storage_path+'|'+(f.id||'');return `<input type="checkbox" class="file-check" data-origin="${origin}" data-id="${esc(f.id||'')}" data-path="${esc(f.storage_path)}" data-name="${esc(f.file_name||f.storage_path)}">`}
function fileRow(f, origin){const url=publicUrl(f.storage_path);return `<div class="file">${fileCheckbox(f,origin)}<img class="thumb" src="${url}" onerror="this.style.opacity=.25" onclick="preview('${esc(url)}')"><div><div class="file-name">${esc(f.file_name||f.storage_path)}</div><div class="muted">page ${esc(f.page_no||'-')} · ${esc(f.storage_path)}</div></div><div class="actions"><button onclick="preview('${esc(url)}')">보기</button></div></div>`}
function renderVersions(){const box=document.getElementById('tabVersions');if(!versions.length){box.innerHTML='<div class="empty">아직 버전이 없습니다. 오른쪽에서 기본/전주1/전주2를 만들거나 새 버전을 추가하세요.</div>';return}let html='<div class="version-grid">';for(const v of versions){const files=dbFiles.filter(f=>String(f.version_id)===String(v.id)).sort((a,b)=>(a.page_no||0)-(b.page_no||0));html+=`<div class="version"><div class="version-head"><div><h3>${esc(v.version_name)} ${v.is_default?'⭐':''}</h3><span class="pill good">Key ${esc(v.score_key||selected.key||'-')}</span><span class="pill">${esc(v.score_type||'코드악보')}</span><span class="pill">${files.length}장</span><span class="pill warn">BPM ${esc(v.bpm_min||'-')}${v.bpm_max&&v.bpm_max!==v.bpm_min?'~'+esc(v.bpm_max):''}</span></div><div><button onclick="makeDefault('${v.id}')">대표</button> <button onclick="editVersionPrompt('${v.id}')">수정</button> <button class="danger" onclick="deleteVersion('${v.id}')">버전삭제</button></div></div><p>${esc(v.memo||'메모 없음')}</p><div class="files">${files.map(f=>fileRow(f,'db')).join('')||'<div class="empty">이 버전에 연결된 파일 없음</div>'}</div></div>`}
html+='</div>';box.innerHTML=html}
function renderUnlinked(){const linked=new Set(dbFiles.map(f=>f.storage_path));const unlinked=storageFiles.filter(f=>!linked.has(f.storage_path));document.getElementById('tabUnlinked').innerHTML=`<div class="notice">Storage에는 있지만 DB 버전에 아직 연결되지 않은 악보입니다. 체크 후 오른쪽에서 버전을 선택하고 이동하세요.</div><div class="files">${unlinked.map(f=>fileRow(f,'storage')).join('')||'<div class="empty">미분류 악보 없음</div>'}</div>`}
function renderRepair(){const storageSet=new Set(storageFiles.map(f=>f.storage_path));const missing=dbFiles.filter(f=>!storageSet.has(f.storage_path));const dupMap={};dbFiles.forEach(f=>{dupMap[f.storage_path]=(dupMap[f.storage_path]||[]).concat(f)});const dups=Object.values(dupMap).filter(a=>a.length>1).flat();document.getElementById('tabRepair').innerHTML=`<div class="notice">이 화면은 삭제보다 점검용입니다. 깨진 연결이나 중복 DB 기록을 먼저 눈으로 확인하세요.</div><h3>DB에는 있는데 Storage 파일 없음</h3><div class="files">${missing.map(f=>fileRow(f,'db')).join('')||'<div class="empty">깨진 DB 연결 없음</div>'}</div><h3>같은 파일이 DB에 중복 연결됨</h3><div class="files">${dups.map(f=>fileRow(f,'db')).join('')||'<div class="empty">중복 연결 없음</div>'}</div><div class="row" style="margin-top:12px"><button class="warn" onclick="removeBrokenDbLinks()">깨진 DB 연결만 제거</button><button class="good" onclick="renumberPages()">현재 버전 페이지 재번호</button></div>`}
async function createVersion(){if(!selected)return toast('곡을 먼저 선택하세요');const name=document.getElementById('newVersionName').value.trim()||'기본';const key=document.getElementById('newVersionKey').value||selected.key||'';const min=Number(document.getElementById('newBpmMin').value)||null;const max=Number(document.getElementById('newBpmMax').value)||min;const payload={song_id:selected.id,version_name:name,score_key:key,score_type:document.getElementById('newVersionType').value,bpm_min:min,bpm_max:max,is_default:versions.length===0,memo:document.getElementById('newVersionMemo').value.trim()};await api('POST','song_score_versions',payload);['newVersionName','newBpmMin','newBpmMax','newVersionMemo'].forEach(id=>document.getElementById(id).value='');toast('버전 추가 완료');log('버전 추가: '+name);await reloadSelected()}
async function createBasicVersions(){if(!selected)return;const names=['기본','전주1','전주2'];let made=0;for(const n of names){if(versions.some(v=>norm(v.version_name)===norm(n)))continue;await api('POST','song_score_versions',{song_id:selected.id,version_name:n,score_key:selected.key||'',score_type:'코드악보',is_default:n==='기본'&&versions.length===0,memo:''});made++}toast(`${made}개 버전 생성`);log('기본 버전 세트 생성');await reloadSelected()}
async function makeDefault(id){const v=versions.find(x=>String(x.id)===String(id));if(!v)return;await api('PATCH',`song_score_versions?song_id=eq.${v.song_id}`,{is_default:false});await api('PATCH',`song_score_versions?id=eq.${id}`,{is_default:true,updated_at:new Date().toISOString()});toast('대표 악보 지정');await reloadSelected()}
async function editVersionPrompt(id){const v=versions.find(x=>String(x.id)===String(id));if(!v)return;const name=prompt('버전명',v.version_name);if(name===null)return;const key=prompt('Key',v.score_key||selected.key||'');if(key===null)return;const memo=prompt('메모',v.memo||'');if(memo===null)return;await api('PATCH',`song_score_versions?id=eq.${id}`,{version_name:name.trim()||v.version_name,score_key:key.trim(),memo:memo.trim(),updated_at:new Date().toISOString()});toast('버전 수정 완료');await reloadSelected()}
async function deleteVersion(id){const files=dbFiles.filter(f=>String(f.version_id)===String(id));if(files.length){toast('파일이 연결된 버전은 먼저 파일을 이동/삭제하세요');return}if(!confirm('빈 버전을 삭제할까요?'))return;await api('DELETE',`song_score_versions?id=eq.${id}`);toast('버전 삭제 완료');await reloadSelected()}
function checkedFiles(){return [...document.querySelectorAll('.file-check:checked')].map(el=>({origin:el.dataset.origin,id:el.dataset.id,path:el.dataset.path,name:el.dataset.name}))}
async function moveCheckedToVersion(){const target=document.getElementById('moveTarget').value;if(!target)return toast('이동할 버전을 선택하세요');const items=checkedFiles();if(!items.length)return toast('파일을 체크하세요');let max=0;try{const rows=await api('GET',`song_score_files?select=page_no&version_id=eq.${target}&order=page_no.desc&limit=1`);max=rows[0]?.page_no||0}catch(e){}for(const item of items){max++;if(item.id){await api('PATCH',`song_score_files?id=eq.${item.id}`,{version_id:target,page_no:max})}else{await api('POST','song_score_files',{version_id:target,song_id:selected.id,storage_path:item.path,file_name:item.name,page_no:max,mime_type:'image/*'})}}await api('PATCH',`songs?id=eq.${selected.id}`,{has_score:true,status:'ready',updated_at:new Date().toISOString()});toast('선택 파일 이동 완료');log(`${items.length}개 파일을 버전으로 이동`);await reloadSelected()}
async function deleteCheckedFiles(){const items=checkedFiles();if(!items.length)return toast('삭제할 파일을 체크하세요');const mode=confirm('Storage 실제 이미지까지 삭제할까요?\n확인: 실제 파일+DB 삭제\n취소: DB 연결만 삭제');try{if(mode){await storageRemove([...new Set(items.map(i=>i.path))]);log('Storage 파일 삭제: '+items.length+'개')}for(const item of items){if(item.id)await api('DELETE',`song_score_files?id=eq.${item.id}`)}toast('삭제 처리 완료');await reloadSelected()}catch(e){toast('삭제 실패');log('삭제 실패: '+e.message)}}
async function removeBrokenDbLinks(){const storageSet=new Set(storageFiles.map(f=>f.storage_path));const missing=dbFiles.filter(f=>!storageSet.has(f.storage_path));if(!missing.length)return toast('제거할 깨진 연결 없음');if(!confirm(`${missing.length}개의 깨진 DB 연결만 제거할까요? 실제 파일 삭제는 하지 않습니다.`))return;for(const f of missing){await api('DELETE',`song_score_files?id=eq.${f.id}`)}toast('깨진 DB 연결 제거 완료');await reloadSelected()}
async function renumberPages(){if(!versions.length)return;for(const v of versions){const files=dbFiles.filter(f=>String(f.version_id)===String(v.id)).sort((a,b)=>(a.page_no||0)-(b.page_no||0)||String(a.created_at).localeCompare(String(b.created_at)));let n=1;for(const f of files){if(f.page_no!==n)await api('PATCH',`song_score_files?id=eq.${f.id}`,{page_no:n});n++}}toast('페이지 번호 정리 완료');await reloadSelected()}
function preview(url){document.getElementById('previewImg').src=url;document.getElementById('previewModal').classList.add('open')}
loadSongs();
